spring.application.name=orbitank-api

# ORACLE DATABASE
spring.datasource.url=${ORACLE_URL}
spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.username=${ORACLE_USER}
spring.datasource.password=${ORACLE_PASSWORD}

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SERVER
server.port=${PORT:8080}

# EMAIL CONFIG (GMAIL) - Variaveis de Ambiente
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Nosso email remetente
orbitank.mail.from=${MAIL_FROM}